### ISSUE TITLE
Logging Joins and Leaves

### ISSUE THREAD

**Issue by NightWolf56** [Fumenoid/JHDBot#14]
Logging user's joins and leaves is pretty nice feature to have in channels. It is much easier than sifting through the Audit log.

**Comment by Liikt** [comment]
But isn't that what Dyno does already?

**Comment by MEhrn00** [comment]
The goal is to get rid of as many bots as we can and just add the features we need from them into the JHD_Bot so yes.

**Comment by Fumenoid** [comment]
Dyno goes down sometimes.
also yes sooner or later we wanna shift most of the things to JHDBot and use rest bot as backup bots

**Comment by Liikt** [comment]
aight makes sense

**Comment by pop-eax** [comment]
this was also done
