### ISSUE TITLE
Use SSL for the verification site

### ISSUE THREAD

**Issue by MEhrn00** [Fumenoid/JHDBot#19]
SSL is pretty much a must when hosting a website. It would be a good idea to add SSL to the webpage before it gets deployed.

**Comment by pop-eax** [comment]
we need to get a domain name before using ssl in order to sign the certs

**Comment by pop-eax** [comment]
we can use the cert bot plugin to make it work with nginx.
I am not sure if we also need to port gunicorn to use ssl

**Comment by pop-eax** [comment]
I think certbot is enough no need to make gunicorn use https

**Comment by pop-eax** [comment]
we will use johnhammond-bot.dev

**Comment by pop-eax** [comment]
edit the /etc/hosts to the ip of the vps

**Comment by Liikt** [comment]
certbot also works with nginx iirc

**Comment by pop-eax** [comment]
we got SSL certs now
