### ISSUE TITLE
Tweak Verification?

### ISSUE THREAD

**Issue by NightWolf56** [Fumenoid/JHDBot#27]
We can tweak the verify command to DM them with the info from finishing welcome and give them member. I think have multiple layers of captcha will make it harder to retain users. Thoughts?

**Comment by pop-eax** [comment]
it would be "secure", but the problem is that we need to consider user experience too

**Comment by MEhrn00** [comment]
Done [https://github.com/Fumenoid/JHDBot/pull/31](https://github.com/Fumenoid/JHDBot/pull/31)
