### ISSUE TITLE
Convert pipenv to requirements.txt

### ISSUE THREAD

**Issue by MEhrn00** [Fumenoid/JHDBot#8]
`pipenv` and `Pipfile` uses significantly more resources for installing python packages as compared to `requirements.txt`. The JHD Bot uses `pipenv` instead of `requirements.txt`. It is recommended to change from `pipenv` to `requirements.txt` for using a docker-based deployment.

**Comment by pop-eax** [comment]
just made a requirement.txt file 
```
discord==1.0.1
python-dotenv==0.14.0
```
now it's time for fume to change stuff

**Comment by MEhrn00** [comment]
Added it with the recent commit [https://github.com/Fumenoid/JHDBot/commit/3d6f3f4a3a17d1ae08e32d119ca684cd1a601610](https://github.com/Fumenoid/JHDBot/commit/3d6f3f4a3a17d1ae08e32d119ca684cd1a601610)
